set nocompatible              " be iMproved, required
filetype off                  " required

" Cleaner way to add bundles:
source ~/.vim/bundles.vim

" Airline related settings
let g:airline_theme = 'solarized'
let g:airline_left_sep = '⮀'
let g:airline_left_alt_sep = '⮁'
let g:airline_right_sep = '⮂'
let g:airline_right_alt_sep = '⮃'

if exists("+cursorline")
    augroup CursorLine
        autocmd!
        autocmd InsertEnter * set cursorline
        autocmd InsertLeave * set nocursorline
        augroup end
endif

" All of your Plugins must be added before the following line
call vundle#end()            " required

" now (after vundle finished) it is save to turn filetype plugins on
filetype plugin indent on    " required

" Encoding
set encoding=utf-8
set fileencoding=utf-8

" Spelling
set spelllang=en,es
syntax enable

" Line Numbers
set number
set numberwidth=4
set cursorline

" Indent
set shiftwidth=4
set softtabstop=4
set expandtab

" Theming
set background=dark
colorscheme solarized
set t_Co=256
set colorcolumn=100
let g:solarized_termcolors=256

" Core
set antialias
set ruler
set title

scriptencoding utf-8
set encoding=utf-8

" Add the virtualenv's site-packages to vim path
if has('python')
py << EOF
import os.path
import sys
import vim
if 'VIRTUAL_ENV' in os.environ:
    project_base_dir = os.environ['VIRTUAL_ENV']
    sys.path.insert(0, project_base_dir)
    activate_this = os.path.join(project_base_dir,
'bin/activate_this.py')
    execfile(activate_this, dict(__file__=activate_this))
EOF
endif

" NerdTree config
map <F2> :NERDTreeToggle<CR>
let NerdTreeIgnore = ['\.pyc$','pycache']
